version: '3'

services:
  houdini:
    working_dir: /app/cmd
    build: .
    depends_on:
      - db
      - redis
    env_file:
      - ./.env
    volumes:
      - ./:/app/
      - go-modules:/go/pkg/mod
    ports:
      - "8086:8086"
    extra_hosts:
      - "host.docker.internal:host-gateway"


  db:
    image: postgres:13.8-alpine
    container_name: houdini-db
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: houdini
    ports:
      - "5437:5432"
    volumes:
      - HOUDINI:/var/lib/postgresql/data
  redis:
    image: redis:latest
    container_name: houdini-redis
    environment:
      REDIS_PASSWORD: redis123
      REDIS_USER: user123
      REDIS_ADDR: redis:6379
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./storage/redis/:/root/redis
      - ./storage/redis/:/usr/local/etc/redis/redis.conf


volumes:
  go-modules:
  HOUDINI: