// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/dilly3/houdini/internal/repository (interfaces: ICommitRepository)
//
// Generated by this command:
//
//	mockgen -destination=internal/server/mocks/commit_mock.go -package=mocks github.com/dilly3/houdini/internal/repository ICommitRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/dilly3/houdini/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockICommitRepository is a mock of ICommitRepository interface.
type MockICommitRepository struct {
	ctrl     *gomock.Controller
	recorder *MockICommitRepositoryMockRecorder
}

// MockICommitRepositoryMockRecorder is the mock recorder for MockICommitRepository.
type MockICommitRepositoryMockRecorder struct {
	mock *MockICommitRepository
}

// NewMockICommitRepository creates a new mock instance.
func NewMockICommitRepository(ctrl *gomock.Controller) *MockICommitRepository {
	mock := &MockICommitRepository{ctrl: ctrl}
	mock.recorder = &MockICommitRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockICommitRepository) EXPECT() *MockICommitRepositoryMockRecorder {
	return m.recorder
}

// DeleteByDate mocks base method.
func (m *MockICommitRepository) DeleteByDate(arg0 context.Context, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByDate", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByDate indicates an expected call of DeleteByDate.
func (mr *MockICommitRepositoryMockRecorder) DeleteByDate(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByDate", reflect.TypeOf((*MockICommitRepository)(nil).DeleteByDate), arg0, arg1, arg2)
}

// GetCommitByID mocks base method.
func (m *MockICommitRepository) GetCommitByID(arg0 context.Context, arg1 string) (*model.CommitInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCommitByID", arg0, arg1)
	ret0, _ := ret[0].(*model.CommitInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCommitByID indicates an expected call of GetCommitByID.
func (mr *MockICommitRepositoryMockRecorder) GetCommitByID(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCommitByID", reflect.TypeOf((*MockICommitRepository)(nil).GetCommitByID), arg0, arg1)
}

// GetCommitsByRepoName mocks base method.
func (m *MockICommitRepository) GetCommitsByRepoName(arg0 context.Context, arg1 string, arg2 int) ([]model.CommitInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCommitsByRepoName", arg0, arg1, arg2)
	ret0, _ := ret[0].([]model.CommitInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCommitsByRepoName indicates an expected call of GetCommitsByRepoName.
func (mr *MockICommitRepositoryMockRecorder) GetCommitsByRepoName(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCommitsByRepoName", reflect.TypeOf((*MockICommitRepository)(nil).GetCommitsByRepoName), arg0, arg1, arg2)
}

// GetLastCommit mocks base method.
func (m *MockICommitRepository) GetLastCommit(arg0 context.Context, arg1 string) (*model.CommitInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLastCommit", arg0, arg1)
	ret0, _ := ret[0].(*model.CommitInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLastCommit indicates an expected call of GetLastCommit.
func (mr *MockICommitRepositoryMockRecorder) GetLastCommit(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastCommit", reflect.TypeOf((*MockICommitRepository)(nil).GetLastCommit), arg0, arg1)
}

// GetTopCommitsAuthorsByCount mocks base method.
func (m *MockICommitRepository) GetTopCommitsAuthorsByCount(arg0 context.Context, arg1 string, arg2 int) ([]model.AuthorCommits, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTopCommitsAuthorsByCount", arg0, arg1, arg2)
	ret0, _ := ret[0].([]model.AuthorCommits)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTopCommitsAuthorsByCount indicates an expected call of GetTopCommitsAuthorsByCount.
func (mr *MockICommitRepositoryMockRecorder) GetTopCommitsAuthorsByCount(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTopCommitsAuthorsByCount", reflect.TypeOf((*MockICommitRepository)(nil).GetTopCommitsAuthorsByCount), arg0, arg1, arg2)
}

// SaveCommit mocks base method.
func (m *MockICommitRepository) SaveCommit(arg0 context.Context, arg1 *model.CommitInfo) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveCommit", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveCommit indicates an expected call of SaveCommit.
func (mr *MockICommitRepositoryMockRecorder) SaveCommit(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveCommit", reflect.TypeOf((*MockICommitRepository)(nil).SaveCommit), arg0, arg1)
}

// SaveCommits mocks base method.
func (m *MockICommitRepository) SaveCommits(arg0 context.Context, arg1 []model.CommitInfo) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveCommits", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveCommits indicates an expected call of SaveCommits.
func (mr *MockICommitRepositoryMockRecorder) SaveCommits(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveCommits", reflect.TypeOf((*MockICommitRepository)(nil).SaveCommits), arg0, arg1)
}
