// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/dilly3/houdini/internal/repository (interfaces: IRepoRepository)
//
// Generated by this command:
//
//	mockgen -destination=internal/server/mocks/repo_mock.go -package=mocks github.com/dilly3/houdini/internal/repository IRepoRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/dilly3/houdini/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockIRepoRepository is a mock of IRepoRepository interface.
type MockIRepoRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIRepoRepositoryMockRecorder
}

// MockIRepoRepositoryMockRecorder is the mock recorder for MockIRepoRepository.
type MockIRepoRepositoryMockRecorder struct {
	mock *MockIRepoRepository
}

// NewMockIRepoRepository creates a new mock instance.
func NewMockIRepoRepository(ctrl *gomock.Controller) *MockIRepoRepository {
	mock := &MockIRepoRepository{ctrl: ctrl}
	mock.recorder = &MockIRepoRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIRepoRepository) EXPECT() *MockIRepoRepositoryMockRecorder {
	return m.recorder
}

// GetRepoByID mocks base method.
func (m *MockIRepoRepository) GetRepoByID(arg0 context.Context, arg1 string) (*model.RepoInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRepoByID", arg0, arg1)
	ret0, _ := ret[0].(*model.RepoInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRepoByID indicates an expected call of GetRepoByID.
func (mr *MockIRepoRepositoryMockRecorder) GetRepoByID(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRepoByID", reflect.TypeOf((*MockIRepoRepository)(nil).GetRepoByID), arg0, arg1)
}

// GetRepoByName mocks base method.
func (m *MockIRepoRepository) GetRepoByName(arg0 context.Context, arg1 string) (*model.RepoInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRepoByName", arg0, arg1)
	ret0, _ := ret[0].(*model.RepoInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRepoByName indicates an expected call of GetRepoByName.
func (mr *MockIRepoRepositoryMockRecorder) GetRepoByName(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRepoByName", reflect.TypeOf((*MockIRepoRepository)(nil).GetRepoByName), arg0, arg1)
}

// GetReposByLanguage mocks base method.
func (m *MockIRepoRepository) GetReposByLanguage(arg0 context.Context, arg1 string, arg2 int) ([]model.RepoInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReposByLanguage", arg0, arg1, arg2)
	ret0, _ := ret[0].([]model.RepoInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReposByLanguage indicates an expected call of GetReposByLanguage.
func (mr *MockIRepoRepositoryMockRecorder) GetReposByLanguage(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReposByLanguage", reflect.TypeOf((*MockIRepoRepository)(nil).GetReposByLanguage), arg0, arg1, arg2)
}

// GetReposByStarCount mocks base method.
func (m *MockIRepoRepository) GetReposByStarCount(arg0 context.Context, arg1 int) ([]model.RepoInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReposByStarCount", arg0, arg1)
	ret0, _ := ret[0].([]model.RepoInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReposByStarCount indicates an expected call of GetReposByStarCount.
func (mr *MockIRepoRepositoryMockRecorder) GetReposByStarCount(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReposByStarCount", reflect.TypeOf((*MockIRepoRepository)(nil).GetReposByStarCount), arg0, arg1)
}

// SaveRepo mocks base method.
func (m *MockIRepoRepository) SaveRepo(arg0 context.Context, arg1 *model.RepoInfo) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveRepo", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveRepo indicates an expected call of SaveRepo.
func (mr *MockIRepoRepositoryMockRecorder) SaveRepo(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveRepo", reflect.TypeOf((*MockIRepoRepository)(nil).SaveRepo), arg0, arg1)
}
